events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # Proxy for relay-go
        location /webhook-events/ {
            proxy_pass http://relay-go:8888;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /emails {
            proxy_pass http://relay-go:8888;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # All other routes go to relay-esp
        location / {
            proxy_pass http://relay-esp:8081;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
